FROM    factorial/drupal-docker:php80-multi-arch
#MAINTAINER Stephan Maximilian Huber <stephan@factorial.io>

RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update --fix-missing && apt-get -y -q install php-xdebug
