ARG BASE_IMAGE_TAG

FROM    factorial/drupal-docker:$BASE_IMAGE_TAG
MAINTAINER stephan@factorial.io

RUN apt-get update && apt-get install -y wget xfonts-base xfonts-75dpi pdftk xz-utils
ARG TARGETARCH
RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_$TARGETARCH.deb
RUN dpkg -i wkhtmltox_0.12.6-1.buster_$TARGETARCH.deb

