name: Build php74 docker images multi-arch

on:
  push:
    paths:
      - 'php/Dockerfile.php-74'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2      
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: create --use
        run: docker buildx create --use
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: buildx ls
        run: docker buildx ls
      - name: build the image
        run: |
          docker buildx create --use          
          docker buildx build --file php/Dockerfile.php-74 --push  --tag factorial/multi-arch:php74-multi-arch --platform linux/amd64,linux/arm64 .



