name: Build php74-xdebug docker images multiarch

on:
  push:
    branches:
      - multi-arch-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: create --use
        run: docker buildx create --use
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: buildx ls
        run: docker buildx ls
      - name: build the image
        run: |
          docker buildx build --file php-xdebug/Dockerfile.php-74 --push \
            --tag factorial/drupal-docker:php74-xdebug-multi-arch \
            --platform linux/amd64,linux/arm64 .
